### ISSUE TITLE
Formalize the error message thrown in server side

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/MyTodoList#14]
For now, the server is just throwing the plain text back to client. We need to formalize the error message and have it implemented in both server and web client.

**Comment by RukaiYu** [comment]
How about in this format: {
errorMessage: strong,
data: object,
statusCode: integer

}
?

**Comment by RukaiYu** [comment]
How about in this format: {
errorMessage: strong,
data: object,
statusCode: integer

}
?

**Comment by LingForCC** [comment]
I think this is good. But need to define statusCode carefully.

**Comment by LingForCC** [comment]
Or statusCode is the standard HTTP status code? If so, I am wondering if we can just include the 

`{
errorCode: 
errorMessage: string,
data: object(optional),
}`

**Comment by RukaiYu** [comment]
If I understand correctly, should we use this format as a standard for all the API response model type? I.e, for 

* createTask api, the response could be:
    * Case success
    ```json
    {
      "message": "task is added successfully.",
      "data": null, // (optional),
      "success": true
    }
    ```
    * Case failed
     ```json
     {
        "message": "Invalid Name.",
        "data": null, // (optional),
        "success": false
     }
     ```


This is good for Front-end, and the AT stuff.

**Comment by LingForCC** [comment]
Yes. We should use this as an API standard. But in this particular case for adding task

- for success I think we should return the task details as you suggested before
- for failed I think we should have following response
```
{
    errorCode: TCE-001(Task Creation Error - Invalid Name),
    errorMessage: string,
    data: object(optional),
}
```

In general, I think for 200 response, we can define whatever makes sense. And for other response, especially for 4xx and 5xx, we should have the standard format as above.

**Comment by LingForCC** [comment]
Reopen this as we need to add a error code generate mechanism

**Comment by LingForCC** [comment]
Trying to setup a ErrorCodeGenerator mechanism with #25
