### ISSUE TITLE
 Add Task

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/MyTodoList#2]
#### Requirement
As an user, I would like to add my task into the system so that I can track my task later.

#### Description
As this is the very first feature of the system, user doesn't even have a way to view the task list. So the idea is to show user a notification that the task is added or not.

**Comment by LingForCC** [comment]
In order to achieve this, looks like we need following few things

- An input box so user can input the task name
- An OK or Add button so user can confirm the adding
- A notification which indicates whether the add is successful or not.

**Comment by RukaiYu** [comment]
What database is chosen to be the storage solution? PostgreSQL seems is a good choice

**Comment by LingForCC** [comment]
> What database is chosen to be the storage solution? PostgreSQL seems is a good choice

I don't know. For this particular feature, we don't any any database yet. I think we can decide later

**Comment by RukaiYu** [comment]
For the task name, do we have a limitation on the length? Now is set to 300 ...
