### ISSUE TITLE
Introduce a test framework for .Net Core WebAPI

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/MyTodoList#20]
We need a test framework to test against the .Net Core WebAPI. The basic idea is to run the API server with an In-Memory database. Then the API can be tested based on the usage of the client(ContractTest).

**Comment by RukaiYu** [comment]
Seems we can use the builtin integration TestServer to build this framework

**Comment by LingForCC** [comment]
Yes. It is introduced with #21

**Comment by LingForCC** [comment]
As now the API test is running pretty fast, it is still included in the normal build process. The CD pipeline will be adjusted if the test takes a lot of time.
