### ISSUE TITLE
Add Automation Test for Feature(Add Task)

### ISSUE THREAD

**Issue by LingForCC** [LingForCC/MyTodoList#9]
This is a follow up task for #2 to complete the automation test.

**Comment by RukaiYu** [comment]
I remember the CI/CD in Azure can setup the Automation Test?

**Comment by LingForCC** [comment]
> I remember the CI/CD in Azure can setup the Automation Test?

@RukaiYu  Yes. I already have it setup as one of the steps in CD. What I mean for this task is to create a full test suite for the feature of 'Add Task'.

**Comment by LingForCC** [comment]
Firstly, Task class is refactored and corresponding tests are added. #17

**Comment by LingForCC** [comment]
Secondly, Test is added to CreateTask method in TaskService #18

**Comment by LingForCC** [comment]
Ideally we should have a test to verify the behaviors of the Add Task API. But as we need to find a test framework for WebAPI(#20), we will leave this part as what it is and implement it in the future.
